### ISSUE TITLE
Dark mode is foobar after Twitter update

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/anatine#104]
I guess Twitter did an update. I'll try looking into it in the coming days. Or if someone else wants to take it. The profile link in the top corner is back as well.

<img width="342" alt="screen shot 2016-07-23 at 13 10 41" src="https://cloud.githubusercontent.com/assets/1913805/17077643/0e44fdcc-50d7-11e6-9f4e-76403fea82ea.png">

**Comment by sindresorhus** [comment]
Thanks for reporting Sam. I won't have time to look into this any time soon though.

**Comment by SamVerschueren** [comment]
Me neither. Have some other projects with higher priority.

**Comment by sindresorhus** [comment]
// @danhp @paulmolluzzo

**Comment by paulmolluzzo** [comment]
@SamVerschueren @sindresorhus @danhp Sorry guys, I've had a few projects on my plate that have kept me busy. If I get a chance to take a look at this I will (and will also update `refined-twitter` as well).

Clearly this is all because Twitter's stack/tooling is generating the class names so our selectors missing. It's almost like we have to go figure the class names all over again. 😞

**Comment by gingerbeardman** [comment]
Out of interest how do I open the web inspector?

**Comment by SamVerschueren** [comment]
The package uses [electron-debug](https://github.com/sindresorhus/electron-debug).

**Comment by SamVerschueren** [comment]
Make sure you run the development mode of Anatine.

**Comment by gingerbeardman** [comment]
How should I do that?

**Comment by paulmolluzzo** [comment]
@gingerbeardman https://github.com/sindresorhus/anatine#dev You want to run the app with `npm start`.

**Comment by gingerbeardman** [comment]
Thanks
