### ISSUE TITLE
scroll-to-tweet html selectors are broken

### ISSUE THREAD

**Issue by janis-kra** [sindresorhus/anatine#108]
While working on #97 I discovered that the two lines in `scroll-to-tweet.js` where HTML elements are fetched seem to be broken:

Line 6:
``` js
const tweets = document.querySelectorAll('._222QxFjc[role="row"]');
```

Line 15:
``` js
const tweetsContainerPadding = Math.ceil(parseInt($('._1nQuzuNK').style.paddingTop.replace('px', ''), 10));
```

The former just returns an empty array but should return the tweets, the latter throws a TypeError.

This can be fixed by using `._2B3_ZDEs[role="row"]` as the tweets selector. No idea which element you want to select on line 15 though.

**Comment by SamVerschueren** [comment]
It's relates to #104. After an update, all the automatic generated classnames are regenerared. So all the selectors are broken.

**Comment by paulmolluzzo** [comment]
Echoing @SamVerschueren and pointing out that this is always going to be super fragile. If someone posts an update and can try to select on something other than a class that we can consider more reliable that'd be great. I almost wonder if traversing along more elements makes sense since the Twitter structure is business-defined and less likely to change. They're not going to change the timeline to something other than a column of rows, right?

**Comment by SamVerschueren** [comment]
> I almost wonder if traversing along more elements makes sense since the Twitter structure is business-defined and less likely to change.

Thought about this as well. We should really look into this to make it more robust.
