### ISSUE TITLE
Request for more keyboard shortcuts

### ISSUE THREAD

**Issue by moeffju** [sindresorhus/anatine#112]
I’m switching from the official Twitter.app and TweetDeck and there are some shortcuts I’m missing, specifically:
- Cmd-D on a tweet to send a direct message to that user
- Cmd-1 to Cmd-5 to jump directly to different tabs (Cmd-1 = Home, Cmd-2 = Interactions, Cmd-3 = DMs, etc.) – if tab is already active, the shortcut would scroll that column to top
- Cmd-Return to send a tweet
- Escape to close an image detail page (I thought this existed but it’s not working for me)
- some way of navigating through the list of tweets, by tweet – official app uses j/k, and then you can Cmd-R to reply, T to retweet, etc.

If this is a quick add it would be super appreciated, or if you could point me to where in the source they’re added, I can prepare a PR, but I have no experience with Electron…

**Comment by sindresorhus** [comment]
It's very easy to add new shortcuts. Nothing Electron specific. I'm just using a library for it. PR welcome :)

See: https://github.com/sindresorhus/anatine/blob/afa05c699b60ef8ed8be9c0420053ed8b06d2a7c/browser.js#L65-L67

-

> Cmd-Return to send a tweet
> Escape to close an image detail page (I thought this existed but it’s not working for me)
> some way of navigating through the list of tweets, by tweet – official app uses j/k, and then you can Cmd-R to reply, T to retweet, etc.

All of these are already implemented, but got broken at some point by CSS changes. `official app uses j/k` is fixed in master.

**Comment by gingerbeardman** [comment]
I'm also missing Cmd-R
