### ISSUE TITLE
Better detection of when React is done

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/anatine#15]
Currently I'm just using a fragile [timeout hack](https://github.com/sindresorhus/anatine/blob/850405be5772cfc22e94fd79a716887ffcb56f72/browser.js#L185-L186). Any suggestions? Any way to hook into React?

**Comment by sindresorhus** [comment]
@paulmolluzzo Any thoughts? This also [applies](https://github.com/sindresorhus/refined-twitter/blob/8453908fb8772cc65bdf866f8ed70cfd40264089/extension/content.js#L67-L68) to `refined-twitter`.

**Comment by paulmolluzzo** [comment]
@sindresorhus I haven't taken a super close look, but the [official React devtools extension](https://github.com/facebook/react-devtools) probably has the best method for hooking into when the app has loaded.

**Comment by sindresorhus** [comment]
I managed to get access to React by putting the following in `browser.js`:

```js
window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = {
	inject: obj => {
		console.log(obj);
	}
};
```

But no idea how to use any of that to figure when the React components are fully loaded.

**Comment by lubien** [comment]
@sindresorhus seem like it uses [chrome.devtools.inspectedWindow.eval()](https://github.com/facebook/react-devtools/blob/master/shells%2Fchrome%2Fsrc%2FcheckForReact.js#L15-L21) to do the job.

I've tried to do this in Anatine and didn't work since it's not inside a extension, I think. Neither a plan `eval` works.

Maybe [gaearon/react-hot-loader](https://github.com/gaearon/react-hot-loader) could help you.

**Comment by paulmolluzzo** [comment]
@sindresorhus I don't think we're going to get away from a `setTimeout` or `setInterval`, but I could totally be wrong. Here's my thinking (BTW, by no means am I a pro at React):

As far as I know, there's nothing in React that means "everything that ought to load has loaded". That's the point of components. React compartmentalizes components so they don't need to know of their surroundings. Every component does have `componentDidMount` of course, but that's just if that particular component mounted. A view doesn't even really have a "complete" scenario, I think. You'd just render the appropriate components based on what the data requires.

Also, I don't think that React extension even tries to figure out if the DOM is "ready". It's kind of irrelevant since it just lists what is rendered with no opinion on whether or not it's "complete" to some .

If we were working on this with access to the React app we'd bind to the `componentDidMount`. It's the most specific to whatever is required. If you need something in a tweet, wait for that component. If it's in the nav, you wait for that (it might be before/after tweets, you don't know).

I'm thinking we should move to a `setInterval` and check for a deeply nested mandatory DOM element. For example, we might check for at least one retweet button on a tweet. That requires: React > base > timeline > single tweet > tweet components

I'm sure there's some other solution, but this is all I've got right now. 😞  

@lubien the first link seems to point out that they're just looking for the React global, which only really tests that it's a React app.

**Comment by sindresorhus** [comment]
@paulmolluzzo Yes, I agree, but my thinking was to listen to all React component initializations and if none has been done for 40ms (arbitrary number) consider it done for now. All I care about are when the initial components are loaded.

That being said, I like your suggestion. Maybe we should just use MutationObserver like we do in `refined-github` and check when what we want is loaded?

**Comment by paulmolluzzo** [comment]
> All I care about are when the initial components are loaded.

Then do a `setInterval` and check for the timeline container? Or the nav? MutationObserver might be too heavy handed.

Something like:

```js
const waitForReact = setInterval(() => {
    // if the header or timeline container exists, init and clear
    if ($('header') || $('._3tixQkQf')) {
       init();
       clearInterval(waitForReact);
    }
}, 200)
```

The only thing is, you have to wait for whatever is required in `init()`. This tripped me up in the scroll to tweet stuff because I couldn't assign the `navHeight` and other constants on initialization, so I just assign them over and over when the event is fired (which is expensive, but whatever).

**Comment by paulmolluzzo** [comment]
@sindresorhus how would you do this with MutationObserver? Look inside the `react-root` for subtree changes? Would you put sort of a "reverse timer" to check for no changes in that period and reset the timer on every change?

**Comment by sindresorhus** [comment]
We only care about the navbar for now, so I would limit it to `#react-root header`. Not sure I get what you mean with `reverse timer` though.

**Comment by paulmolluzzo** [comment]
@sindresorhus  What I was trying to get at is that with MutationObserver it starts on a change, so you'd start the timer on a change to the subtree and if a change occurs before the timer runs out you'd restart the timer. The timer ending would fire the desired function (i.e. `init()`).

This is sort of "reverse" of the `clearInterval` pattern I mentioned, which would set a timer and then stop the timer if something came into existence.

Made a PR: #42 

I guess it's just a bad description...?

![justin-kate-mckinnon-who-knows-l4KieBrGOpzpR2d1K](https://camo.githubusercontent.com/4bd2ebb26d58ee4e6057e44618c153dd84ec6026/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6c344b69654272474f707a70523264314b2f67697068792e676966>)
