### ISSUE TITLE
Disappearing tweets

### ISSUE THREAD

**Issue by awesomegithubusername** [sindresorhus/anatine#59]
Hi; First things first, great work! The app is faster than Twitter's website. I'm experiencing a weird behavior, though. Tweets started to disappear as I scrolled down. They reappear if I scroll up:

![anatine3](https://cloud.githubusercontent.com/assets/13295503/15408757/ba783f10-1e09-11e6-8163-f75c6ac1015b.gif)

Anatine 0.3.0
Electron 1.0.1
win32 ia32 6.1.7601

**Comment by SamVerschueren** [comment]
Wow that is really odd. And you don't experience that in the browser?

**Comment by awesomegithubusername** [comment]
no, it works fine in the browser, albeit a little slower.

**Comment by paulmolluzzo** [comment]
I don't have Windows, so I can't test locally, but if @awesomegithubusername can take a look at this and screenshot or something it might help:

Twitter is replacing the list of tweets as you scroll down (as opposed to appending), so it's possible the timeline is out of sync because of a scroll position miscommunication or something.

What you could do is open the Developer Tools (CMD+Option+I on a Mac) and drill down to the timeline area. Then as you scroll, see what happens to the DOM. My guess is this is either 1) padding/margin pushing the page down too far or 2) the offset from the top telling Twitter you're further down on the page than you really are.

![](http://g.recordit.co/sWZ5oNwY6U.gif)

**Comment by awesomegithubusername** [comment]
> What you could do is open the Developer Tools (CMD+Option+I on a Mac) and drill down to the timeline area


Thanks for your reply @paulmolluzzo, but I can't open the Dev Tools (tried both **Ctrl+Alt+I** and **Ctrl+Shift+ I**).

**Comment by paulmolluzzo** [comment]
@awesomegithubusername It's the same keyboard shortcut for opening dev tools in Chrome.. Are you using an installed version or the run that runs when you do `npm start`?  Maybe if you use the installed from binary version dev tools is not available?

-----

@sindresorhus Is it overkill to have labels for Windows/Mac/Linux?

**Comment by danhp** [comment]
We don't give built version access to the dev tools

**Comment by awesomegithubusername** [comment]
> We don't give built version access to the dev tools

Oh I see, I'm running a built version.

**Comment by paulmolluzzo** [comment]
Didn't know that, thanks @danhp

**Comment by awesomegithubusername** [comment]
I used your dark mode CSS in Twitter mobile site (using Stylish extension). No more disapearing tweets:

![6sbfqwm](https://cloud.githubusercontent.com/assets/13295503/15434620/a3ac9e74-1eaf-11e6-8f3f-c836a9eb1b7d.gif)

**Comment by sindresorhus** [comment]
I just did a new release with an upgrade Electron version. Can you try it out and see if the issue is still there?

https://github.com/sindresorhus/anatine/releases

**Comment by awesomegithubusername** [comment]
Thanks for the update, @sindresorhus. Unfortunately, I keep getting that weird behavior.

**Comment by awesomegithubusername** [comment]
Test it in my work machine. It works fine.
