### ISSUE TITLE
Separate buttons for Retweet and Quote

### ISSUE THREAD

**Issue by AmrEldib** [sindresorhus/anatine#63]
Instead of two clicks, one click is faster. There's plenty of space for it.

**Comment by sindresorhus** [comment]
There's probably a good reason Twitter didn't do this themselves. Having a confirm is also useful to prevent accidental retweets. I accidentally tap like on a lot of tweets when scrolling through my feed.

**Comment by paulmolluzzo** [comment]
I agree about the value of the having that confirmation. Besides that, I don't even know how we'd go about accomplishing this since we'd have to generate the HTML for the extra button and bind an event to it that we don't even know what the function is. That event listener is bound with React.

I'm not interested, except that I'm curious to know how someone would do it.

**Comment by sindresorhus** [comment]
Alright. Passing on this.

**Comment by sindresorhus** [comment]
@paulmolluzzo Could probably have had that button just `el.click()` the quote or RT button in the retweet dialog.
