### ISSUE TITLE
Fix TODOs

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/anatine#97]
Fix TODO's in the code.

```
browser.js
21:	// TODO: these lines can probably be simplified, but I can't think right now

scroll-to-tweet.js
9:		const keyCode = event.charCode; // TODO: replace with key when Chrome 51 is out https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
28:			// TODO: Replace with for...of loop when Chrome 51 is released https://mobile.twitter.com/chromiumdev/status/717736215433256960
```

**Comment by forivall** [comment]
FYI, electron > 1.2.0 is running chrome 51, so the scroll-to-tweet TODOs can be resolved.

**Comment by sindresorhus** [comment]
@forivall Yup, that's why I opened this issue now.

**Comment by janis-kra** [comment]
I had some free time today and pondered on a simpler solution for the `changeTab` function in brower.js, I'll submit a PR soon

**Comment by janis-kra** [comment]
Okay, so I fiddled around with the scroll-to-tweet stuff, but discovered that the jquery selectors for fetching the `tweets` and the `tweetsContainerPadding` are kind of broken, which obviously also breaks the whole scroll-to-tweet functionality. I'll open a new issue for that.

I'll go ahead and submit a PR with the fix for browser.js to get that part of this issue off the table.

**Comment by sindresorhus** [comment]
> but I'm not sure how you would want to use a for..of loop there, as both the tweet and the index parameters are used but for..of would only supply a tweet, no index.

```js
const arr = ['foo', 'bar'];

for (const [i, el] of arr.entries()) {
  console.log(i, el);
}
```
